import { useMemo, useState } from "react";
import { Activity, ArrowDownRight, ArrowUpRight, BarChart3, ClipboardList, ExternalLink, Gauge, Landmark, RefreshCw, ShieldCheck, TrendingUp, WalletCards } from "lucide-react";
import CryptoTerminal from "@/components/CryptoTerminal";
import { trpc } from "@/lib/trpc";
import { CRYPTO_MARKET_OPTIONS, type CryptoMarket } from "@shared/crypto";

function price(value: number | null | undefined) { if (value === null || value === undefined || !Number.isFinite(value)) return "—"; const digits = value >= 1_000 ? 2 : value >= 1 ? 4 : 6; return `$${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: digits })}`; }
function compact(value: number | null | undefined) { if (value === null || value === undefined || !Number.isFinite(value)) return "—"; if (Math.abs(value) >= 1_000_000_000) return `${(value / 1_000_000_000).toFixed(2)}B`; if (Math.abs(value) >= 1_000_000) return `${(value / 1_000_000).toFixed(2)}M`; if (Math.abs(value) >= 1_000) return `${(value / 1_000).toFixed(2)}K`; return value.toFixed(2); }

function MarketRadar() {
  const [market, setMarket] = useState<CryptoMarket>("global-spot");
  const liquidPairs = trpc.crypto.tickers.useQuery({ market, limit: 12 }, { retry: false, refetchInterval: 30_000 });
  const topMove = useMemo(() => [...(liquidPairs.data ?? [])].sort((left, right) => Math.abs(right.changePct ?? 0) - Math.abs(left.changePct ?? 0))[0], [liquidPairs.data]);
  const marketLabel = CRYPTO_MARKET_OPTIONS.find(item => item.value === market)?.shortLabel ?? "Binance";

  return <section className="binance-card binance-radar"><div className="binance-card-head"><div><span className="binance-kicker">PUBLIC MARKET SCAN</span><h2>Liquid USDT pairs</h2></div><button aria-label="Refresh liquid-pair scan" onClick={() => void liquidPairs.refetch()}><RefreshCw size={14} className={liquidPairs.isFetching ? "spin" : ""} /></button></div><div className="binance-tabs" role="tablist" aria-label="Market discovery venue">{CRYPTO_MARKET_OPTIONS.map(option => <button key={option.value} className={market === option.value ? "active" : ""} onClick={() => setMarket(option.value)}>{option.shortLabel}</button>)}</div>{liquidPairs.isLoading ? <div className="binance-empty">Loading public market data…</div> : liquidPairs.data?.length ? <><div className="radar-focus"><span>FASTEST MOVE IN LIQUID SET</span><b>{topMove?.symbol ?? "—"}</b><strong className={(topMove?.changePct ?? 0) >= 0 ? "up" : "down"}>{(topMove?.changePct ?? 0) >= 0 ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}{topMove?.changePct === null || topMove?.changePct === undefined ? "—" : `${topMove.changePct >= 0 ? "+" : ""}${topMove.changePct.toFixed(2)}%`}</strong></div><div className="binance-market-table"><div className="binance-market-row table-heading"><span>PAIR</span><span>LAST</span><span>24H</span><span>QUOTE VOL</span></div>{liquidPairs.data.map(item => <div className="binance-market-row" key={`${market}-${item.symbol}`}><b>{item.symbol}</b><span>{price(item.price)}</span><span className={(item.changePct ?? 0) >= 0 ? "up" : "down"}>{item.changePct === null || item.changePct === undefined ? "—" : `${item.changePct >= 0 ? "+" : ""}${item.changePct.toFixed(2)}%`}</span><span>{compact(item.quoteVolume)}</span></div>)}</div></> : <div className="binance-empty">{marketLabel} liquid-pair data is currently unavailable. No synthetic market list is shown.</div>}</section>;
}

function PaperPlan() {
  const [entry, setEntry] = useState("0");
  const [invalidation, setInvalidation] = useState("0");
  const [target, setTarget] = useState("0");
  const [riskBudget, setRiskBudget] = useState("25");
  const values = useMemo(() => ({ entry: Number(entry), invalidation: Number(invalidation), target: Number(target), riskBudget: Number(riskBudget) }), [entry, invalidation, riskBudget, target]);
  const unitRisk = values.entry > 0 && values.invalidation > 0 ? Math.abs(values.entry - values.invalidation) : 0;
  const quantity = unitRisk > 0 && values.riskBudget > 0 ? values.riskBudget / unitRisk : 0;
  const reward = values.entry > 0 && values.target > 0 ? Math.abs(values.target - values.entry) : 0;
  const multiple = unitRisk > 0 ? reward / unitRisk : 0;

  return <section className="binance-card paper-plan"><div className="binance-card-head"><div><span className="binance-kicker">PAPER ONLY</span><h2>Trade plan calculator</h2></div><span className="paper-state"><ShieldCheck size={12} /> NO ORDERS</span></div><p>Plan risk and sizing locally. This form never submits a Binance order or accesses an account.</p><div className="plan-input-grid"><label>ENTRY<input inputMode="decimal" value={entry} onChange={event => setEntry(event.target.value)} /></label><label>INVALIDATION<input inputMode="decimal" value={invalidation} onChange={event => setInvalidation(event.target.value)} /></label><label>TARGET<input inputMode="decimal" value={target} onChange={event => setTarget(event.target.value)} /></label><label>RISK BUDGET (USDT)<input inputMode="decimal" value={riskBudget} onChange={event => setRiskBudget(event.target.value)} /></label></div><div className="plan-metrics"><div><span>UNIT RISK</span><b>{unitRisk > 0 ? price(unitRisk) : "—"}</b></div><div><span>SIZE</span><b>{quantity > 0 ? quantity.toFixed(5) : "—"}</b></div><div><span>R : R</span><b className={multiple >= 1 ? "up" : "muted"}>{multiple > 0 ? `${multiple.toFixed(2)}R` : "—"}</b></div></div><div className="plan-footer"><ClipboardList size={13} /><span>Planning only · order execution is disabled</span></div></section>;
}

export default function BinanceDashboard() {
  return <div className="binance-app"><header className="binance-nav"><a className="binance-wordmark" href="/binance" aria-label="Binance public-data dashboard"><span className="binance-mark">◆</span> BINANCE <small>PUBLIC TERMINAL</small></a><nav className="binance-dashboard-switcher" aria-label="Choose a dashboard"><a href="/"><span className="switcher-desktop-label">U.S. Equities Dashboard</span><span className="switcher-mobile-label">U.S. Equities</span></a><a href="/binance" aria-current="page"><span className="switcher-desktop-label">Binance Crypto Dashboard</span><span className="switcher-mobile-label">Binance Crypto</span></a></nav><div className="binance-nav-status"><span><Activity size={12} /> LIVE PUBLIC DATA</span><span><ShieldCheck size={12} /> NO ACCOUNT</span></div></header><main className="binance-shell"><section className="binance-hero"><div><span className="binance-kicker">DEDICATED MARKET INTELLIGENCE</span><h1>Binance public-data dashboard</h1><p>Monitor live crypto markets, chart verified provider bars, and prepare risk-managed paper plans without connecting an account or exposing a credential.</p></div><div className="binance-trust-grid"><div><Landmark size={16} /><span>VENUES</span><b>3</b><small>Global Spot · Futures · US</small></div><div><Gauge size={16} /><span>DATA MODE</span><b>LIVE</b><small>Browser-session streams</small></div><div><WalletCards size={16} /><span>ACCOUNT</span><b>NONE</b><small>No balances or credentials</small></div></div></section><div className="binance-boundary"><ShieldCheck size={15} /><div><b>Public market intelligence only.</b><span>This dashboard has no account connection, live order, transfer, withdrawal, leverage, margin, or prediction-trading control.</span></div></div><section className="binance-terminal-grid"><div className="binance-terminal-main"><CryptoTerminal /></div><aside id="market-radar"><MarketRadar /></aside></section><section className="binance-lower-grid"><div id="paper-plan"><PaperPlan /></div><section className="binance-card data-policy"><div className="binance-card-head"><div><span className="binance-kicker">DATA INTEGRITY</span><h2>What this dashboard uses</h2></div><BarChart3 size={18} /></div><div className="policy-list"><div><TrendingUp size={14} /><div><b>Provider-returned values</b><span>Quotes, 24h statistics, candles, and aggregate trades are shown only when public Binance endpoints return them.</span></div></div><div><ShieldCheck size={14} /><div><b>No synthetic account data</b><span>Balances, positions, orders, and trade history are absent because no account API is connected.</span></div></div><div><ExternalLink size={14} /><div><b>Paper plan, not a broker</b><span>The calculator provides sizing context only; it cannot submit, route, or modify any order.</span></div></div></div></section></section></main></div>;
}
