import type { MarketBar, MarketDataProvider, MarketQuote, MarketTrade } from "@shared/scanner";
import { fetchWithTimeout } from "./production";
import { updateProviderHealth } from "./db";

const baseUrl = "https://finnhub.io/api/v1";
const socketUrl = "wss://ws.finnhub.io";

type FinnhubQuote = { c?: number; d?: number; dp?: number; h?: number; l?: number; pc?: number; t?: number };
type FinnhubCandle = { c?: number[]; h?: number[]; l?: number[]; o?: number[]; t?: number[]; v?: number[]; vwap?: number[]; s?: string };
export type FinnhubNewsItem = { category?: string; datetime?: number; headline: string; id?: number; related?: string; source?: string; summary?: string; url?: string };

function key() { const value = process.env.FINNHUB_API_KEY; if (!value) throw new Error("FINNHUB_API_KEY is not configured"); return value; }
function unavailable(symbol: string, reason: string): MarketQuote { return { symbol, price: 0, bid: 0, ask: 0, changePct: 0, volume: 0, rvol: 0, floatM: 0, marketCapM: 0, dollarVolumeM: 0, vwap: 0, sessionHigh: 0, sessionLow: 0, halted: false, lastUpdated: Date.now(), source: "unavailable", providerError: reason }; }
export function normalizeFinnhubQuote(body: FinnhubQuote, symbol: string): MarketQuote { const price = body.c ?? 0; return { symbol, price, bid: price, ask: price, changePct: body.dp ?? 0, volume: 0, rvol: 0, floatM: 0, marketCapM: 0, dollarVolumeM: 0, vwap: price, sessionHigh: body.h ?? price, sessionLow: body.l ?? price, halted: false, lastUpdated: body.t ? body.t * 1000 : Date.now(), source: "finnhub" }; }
export function normalizeFinnhubCandle(body: FinnhubCandle, symbol: string): MarketBar[] { if (body.s !== "ok") return []; return (body.t ?? []).map((timestamp, i) => ({ symbol, open: body.o?.[i] ?? 0, close: body.c?.[i] ?? 0, high: body.h?.[i] ?? 0, low: body.l?.[i] ?? 0, volume: body.v?.[i] ?? 0, vwap: body.vwap?.[i] ?? body.c?.[i] ?? 0, start: timestamp * 1000, end: timestamp * 1000 + 60_000 })); }

export async function fetchFinnhubQuote(symbol: string, token = key()): Promise<MarketQuote> { try { const response = await fetchWithTimeout(`${baseUrl}/quote?symbol=${encodeURIComponent(symbol)}&token=${encodeURIComponent(token)}`); if (!response.ok) return unavailable(symbol, `Finnhub quote request failed: ${response.status}`); const result = normalizeFinnhubQuote(await response.json() as FinnhubQuote, symbol); return result.price > 0 ? result : unavailable(symbol, "Finnhub returned no current quote"); } catch (error) { return unavailable(symbol, error instanceof Error ? error.message : "Finnhub quote request failed"); } }

export async function finnhubNews(symbol: string, from: string, to: string) { const response = await fetchWithTimeout(`${baseUrl}/company-news?symbol=${encodeURIComponent(symbol)}&from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}&token=${encodeURIComponent(key())}`); if (!response.ok) throw new Error(`Finnhub news request failed: ${response.status}`); const items = await response.json() as FinnhubNewsItem[]; return items.map((item, index) => ({ id: String(item.id ?? `${symbol}-${item.datetime ?? index}`), title: item.headline, article_url: item.url ?? "", published_utc: new Date((item.datetime ?? Date.now() / 1000) * 1000).toISOString(), tickers: item.related ? item.related.split(",").filter(Boolean) : [symbol], publisher: { name: item.source ?? "Finnhub" }, description: item.summary })); }

export class FinnhubMarketDataProvider implements MarketDataProvider {
  async getQuotes(symbols: string[]) { const started = Date.now(); const results = await Promise.all(symbols.map(symbol => fetchFinnhubQuote(symbol, key()))); const unavailableCount = results.filter(item => item.source === "unavailable").length; await updateProviderHealth({ provider: "finnhub", status: unavailableCount === 0 ? "healthy" : unavailableCount === results.length ? "offline" : "degraded", latencyMs: Date.now() - started, error: unavailableCount ? `${unavailableCount}/${results.length} Finnhub quotes unavailable` : undefined }); return results; }
  async getBars(symbol: string, from: string, to: string) { const start = Math.floor(new Date(from).getTime() / 1000); const end = Math.floor(new Date(to).getTime() / 1000) + 86_400; const response = await fetchWithTimeout(`${baseUrl}/stock/candle?symbol=${encodeURIComponent(symbol)}&resolution=1&from=${start}&to=${end}&token=${encodeURIComponent(key())}`); if (!response.ok) throw new Error(`Finnhub candle request failed: ${response.status}`); return normalizeFinnhubCandle(await response.json() as FinnhubCandle, symbol); }
  async getTrades(symbol: string, from: string, _to: string): Promise<MarketTrade[]> { const response = await fetchWithTimeout(`${baseUrl}/stock/tick?symbol=${encodeURIComponent(symbol)}&date=${encodeURIComponent(from.slice(0, 10))}&limit=1000&skip=0&token=${encodeURIComponent(key())}`); if (!response.ok) throw new Error(`Finnhub tick request failed: ${response.status}`); const body = await response.json() as { p?: number[]; v?: number[]; t?: number[]; s?: string }; if (body.s && body.s !== "ok") return []; return (body.p ?? []).map((price, index) => ({ symbol, price, size: body.v?.[index] ?? 0, timestamp: body.t?.[index] ?? Date.now() })); }
  subscribe(symbols: string[], onQuote: (quote: MarketQuote) => void, onTrade?: (trade: MarketTrade) => void) { let closed = false; let socket: WebSocket | null = null; try { socket = new WebSocket(`${socketUrl}?token=${encodeURIComponent(key())}`); socket.addEventListener("open", () => { for (const symbol of symbols.slice(0, 50)) socket?.send(JSON.stringify({ type: "subscribe", symbol })); }); socket.addEventListener("message", event => { const payload = JSON.parse(String(event.data)) as { type?: string; data?: Array<{ s?: string; p?: number; v?: number; t?: number }> }; if (payload.type !== "trade") return; for (const item of payload.data ?? []) if (item.s && item.p) { const quoteValue = normalizeFinnhubQuote({ c: item.p, t: item.t ? item.t / 1000 : undefined }, item.s); onQuote(quoteValue); onTrade?.({ symbol: item.s, price: item.p, size: item.v ?? 0, timestamp: item.t ?? Date.now() }); } }); } catch { /* REST remains available when WebSocket is unavailable. */ } return () => { closed = true; if (!closed) return; socket?.close(); socket = null; }; }
}

export const finnhubProvider = new FinnhubMarketDataProvider();
