import { z } from "zod";

export const BOT_DEFAULTS = { market: "global-spot", symbols: ["BTCUSDT", "ETHUSDT", "SOLUSDT"], scheduleMinutes: 5, riskPct: 1, dailyLossStopPct: 3, maxOpenPositions: 3 } as const;
export const PAPER_SCALPING_STRATEGY = "scalp_momentum" as const;
export const PAPER_BOT_STRATEGIES = [PAPER_SCALPING_STRATEGY, "fast_momentum", "range_reversion", "learning_mode"] as const;
export type PaperBotStrategy = typeof PAPER_BOT_STRATEGIES[number];
export const HOLD_CATEGORIES = ["timeframe_conflict", "low_volatility", "no_qualified_setup", "risk_guard", "model_unavailable"] as const;
export type HoldCategory = typeof HOLD_CATEGORIES[number];

export const botDecisionSchema = z.object({ action: z.enum(["buy", "sell", "hold"]), symbol: z.string().regex(/^[A-Z0-9]{5,24}$/), confidence: z.number().min(0).max(1), stopPrice: z.number().positive().nullable(), targetPrice: z.number().positive().nullable(), reason: z.string().min(1).max(600), nextCandle: z.object({ direction: z.enum(["up", "down", "flat"]), probability: z.number().min(0).max(1), reason: z.string().min(1).max(280) }).nullable().optional(), holdCategory: z.enum(HOLD_CATEGORIES).nullable().optional(), learningFallback: z.boolean().optional() });
export type BotDecision = z.infer<typeof botDecisionSchema>;
export type BotAccount = { equity: number; buyingPower: number; dailyStartEquity: number; positions: Array<{ symbol: string; quantity: number; averageCost: number }> };
export type ScalpMarketContext = { oneMinute: { bars: number; changePct: number | null }; fiveMinute: { bars: number; changePct: number | null }; fifteenMinute: { bars: number; changePct: number | null } };

export function noTradeDeepSeekDecision(symbol: string, reason: string): BotDecision { return { action: "hold", symbol, confidence: 0, stopPrice: null, targetPrice: null, reason, nextCandle: null, holdCategory: "model_unavailable" }; }
export function parseDeepSeekDecisionContent(content: string | null | undefined, symbol: string): BotDecision { const normalized = content?.trim(); if (!normalized) return noTradeDeepSeekDecision(symbol, "DeepSeek returned no decision content; no simulated order was created"); const json = normalized.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, ""); try { const parsed = botDecisionSchema.safeParse(JSON.parse(json)); return parsed.success ? parsed.data : noTradeDeepSeekDecision(symbol, "DeepSeek returned an invalid decision schema; no simulated order was created"); } catch { return noTradeDeepSeekDecision(symbol, "DeepSeek returned malformed JSON; no simulated order was created"); } }
export function constrainDecisionToConfiguredSymbols(decision: BotDecision, configuredSymbols: string[]): BotDecision { const fallbackSymbol = configuredSymbols[0] ?? BOT_DEFAULTS.symbols[0]; return configuredSymbols.includes(decision.symbol) ? decision : noTradeDeepSeekDecision(fallbackSymbol, "DeepSeek did not return exactly one configured pair; the run is recorded as hold and no simulated order was created"); }
export function toUtcDateKey(now = new Date()) { return now.toISOString().slice(0, 10); }
export function isDailyLossStopped(account: BotAccount, stopPct: number) { return account.equity <= account.dailyStartEquity * (1 - stopPct / 100); }

const enoughBars = (context: ScalpMarketContext | undefined) => Boolean(context && context.oneMinute.bars >= 12 && context.fiveMinute.bars >= 12 && context.fifteenMinute.bars >= 12);
const strategyPriceGuards = (decision: BotDecision, markPrice: number, stopLossPct = 0.5, takeProfitRatio = 1.5) => { if (!decision.stopPrice || !decision.targetPrice || decision.stopPrice >= markPrice || decision.targetPrice <= markPrice) return "Paper buy requires a stop below and target above the provider mark"; const stopDistance = ((markPrice - decision.stopPrice) / markPrice) * 100; const rewardRisk = (decision.targetPrice - markPrice) / (markPrice - decision.stopPrice); if (stopDistance < .03 || stopDistance > .75) return `Paper strategy stop distance must be between 0.03% and 0.75% (configured: ${stopLossPct.toFixed(2)}%)`; if (rewardRisk < takeProfitRatio) return `Paper strategy target requires at least ${takeProfitRatio.toFixed(1)}:1 simulated reward-to-risk`; return undefined; };

export function deriveHoldCategory(context: ScalpMarketContext | undefined): HoldCategory { if (!enoughBars(context)) return "model_unavailable"; const values = [context!.oneMinute.changePct ?? 0, context!.fiveMinute.changePct ?? 0, context!.fifteenMinute.changePct ?? 0]; const meaningful = .04; if (values.every(value => Math.abs(value) < meaningful)) return "low_volatility"; const hasUp = values.some(value => value > meaningful); const hasDown = values.some(value => value < -meaningful); return hasUp && hasDown ? "timeframe_conflict" : "no_qualified_setup"; }
export function holdDiagnostic(category: HoldCategory | null | undefined) { return ({ timeframe_conflict: "Hold: 1m, 5m, and 15m momentum conflict", low_volatility: "Hold: low volatility inside the neutral zone", no_qualified_setup: "Hold: no qualified setup under the selected paper strategy", risk_guard: "Hold: paper risk guard prevented a new order", model_unavailable: "Hold: model or provider context was unavailable" } as const)[category ?? "model_unavailable"]; }
export function attachHoldDiagnostic(decision: BotDecision, context: ScalpMarketContext | undefined): BotDecision { return decision.action === "hold" ? { ...decision, holdCategory: decision.holdCategory ?? deriveHoldCategory(context) } : decision; }
export type RangeRegime = "range" | "trend" | "unavailable";
export function detectRangeRegime(context: ScalpMarketContext | undefined): RangeRegime { if (!enoughBars(context)) return "unavailable"; const five = context!.fiveMinute.changePct ?? 0, fifteen = context!.fifteenMinute.changePct ?? 0; return Math.abs(five) <= .4 && Math.abs(fifteen) <= .7 ? "range" : "trend"; }
export function rangeInactiveHold(symbol: string, regime: RangeRegime): BotDecision { return { action: "hold", symbol, confidence: 0, stopPrice: null, targetPrice: null, reason: regime === "trend" ? "Range Reversion mode inactive: 5m/15m movement is trending rather than contained" : "Range Reversion mode inactive: sufficient provider bars are unavailable", nextCandle: null, holdCategory: regime === "unavailable" ? "model_unavailable" : "no_qualified_setup" }; }

export function buildRiskManagedPaperOrder(input: { decision: BotDecision; markPrice: number; account: BotAccount; riskPct: number; maxOpenPositions: number }) { const { decision, markPrice, account, riskPct, maxOpenPositions } = input; if (!Number.isFinite(markPrice) || markPrice <= 0) return { allowed: false as const, reason: "Current provider mark is unavailable" }; const position = account.positions.find(item => item.symbol === decision.symbol); if (decision.action === "hold") return { allowed: false as const, reason: "AI selected hold" }; if (decision.action === "sell") { if (!position || position.quantity <= 0) return { allowed: false as const, reason: "No simulated spot position is available to sell" }; return { allowed: true as const, side: "sell" as const, quantity: position.quantity, stopPrice: null, targetPrice: decision.targetPrice }; } if (position) return { allowed: false as const, reason: "A simulated position already exists for this pair" }; if (account.positions.length >= maxOpenPositions) return { allowed: false as const, reason: "Maximum open simulated positions reached" }; if (!decision.stopPrice || decision.stopPrice >= markPrice) return { allowed: false as const, reason: "Buy decisions require a provider-valid stop below the current mark" }; const riskBudget = account.equity * (riskPct / 100); const unitRisk = markPrice - decision.stopPrice; const quantity = Math.min(riskBudget / unitRisk, account.buyingPower / markPrice, (account.equity * .2) / markPrice); if (!Number.isFinite(quantity) || quantity <= 0) return { allowed: false as const, reason: "Insufficient simulated buying power" }; return { allowed: true as const, side: "buy" as const, quantity, stopPrice: decision.stopPrice, targetPrice: decision.targetPrice }; }
export function coerceLearningDecision(input: { decision: BotDecision; markPrice: number; hasPosition: boolean }) { const { decision, markPrice, hasPosition } = input; if (!Number.isFinite(markPrice) || markPrice <= 0) return noTradeDeepSeekDecision(decision.symbol, "Learning simulation needs a valid live provider mark"); const action = hasPosition ? "sell" as const : "buy" as const; const needsFallback = decision.action === "hold" || decision.action !== action; return { ...decision, action, confidence: Math.max(.5, decision.confidence), stopPrice: action === "buy" ? (decision.stopPrice && decision.stopPrice < markPrice ? decision.stopPrice : markPrice * .99) : null, targetPrice: action === "buy" ? (decision.targetPrice && decision.targetPrice > markPrice ? decision.targetPrice : markPrice * 1.01) : decision.targetPrice, reason: needsFallback ? `${decision.reason} Learning mode converted this into a simulated ${action} to demonstrate the paper order lifecycle.` : decision.reason, holdCategory: null, learningFallback: needsFallback }; }
export function buildLearningPaperOrder(input: { decision: BotDecision; markPrice: number; account: BotAccount }) { const { decision, markPrice, account } = input; if (!Number.isFinite(markPrice) || markPrice <= 0) return { allowed: false as const, reason: "Current provider mark is unavailable" }; const position = account.positions.find(item => item.symbol === decision.symbol); if (decision.action === "sell") { if (!position || position.quantity <= 0) return { allowed: false as const, reason: "Learning simulation cannot close a missing paper position" }; return { allowed: true as const, side: "sell" as const, quantity: position.quantity, stopPrice: null, targetPrice: decision.targetPrice }; } if (decision.action !== "buy") return { allowed: false as const, reason: "Learning simulation needs a buy or sell decision" }; if (position) return { allowed: false as const, reason: "Learning simulation expected a close decision for the existing paper position" }; const quantity = (account.buyingPower * .1) / markPrice; if (!Number.isFinite(quantity) || quantity <= 0) return { allowed: false as const, reason: "Insufficient simulated buying power" }; return { allowed: true as const, side: "buy" as const, quantity, stopPrice: decision.stopPrice, targetPrice: decision.targetPrice }; }

export function assessScalpingDecision(input: { decision: BotDecision; markPrice: number; context: ScalpMarketContext | undefined; confidenceThreshold?: number; stopLossPct?: number; takeProfitRatio?: number }) { const { decision, markPrice, context, confidenceThreshold = 0.6, stopLossPct = 0.5, takeProfitRatio = 1.5 } = input; if (decision.action === "hold") return { allowed: true as const }; if (decision.confidence < confidenceThreshold) return { allowed: false as const, reason: `Scalping filter requires at least ${confidenceThreshold.toFixed(2)} model confidence` }; if (!enoughBars(context)) return { allowed: false as const, reason: "Scalping filter requires sufficient 1m, 5m, and 15m provider bars" }; const one = context!.oneMinute.changePct ?? 0, five = context!.fiveMinute.changePct ?? 0, fifteen = context!.fifteenMinute.changePct ?? 0; if (decision.action === "buy") { if (one < .05 || five < 0 || fifteen < 0) return { allowed: false as const, reason: "Scalp Momentum requires positive 1m momentum with 5m/15m confirmation" }; const issue = strategyPriceGuards(decision, markPrice, stopLossPct, takeProfitRatio); return issue ? { allowed: false as const, reason: issue } : { allowed: true as const }; } return one > -.05 || five > 0 || fifteen > 0 ? { allowed: false as const, reason: "Scalp Momentum sell requires negative 1m momentum with 5m/15m confirmation" } : { allowed: true as const }; }
export function assessFastMomentumDecision(input: { decision: BotDecision; markPrice: number; context: ScalpMarketContext | undefined; confidenceThreshold?: number; momentumThreshold?: number; stopLossPct?: number; takeProfitRatio?: number }) { const { decision, markPrice, context, confidenceThreshold = 0.6, momentumThreshold = 0.04, stopLossPct = 0.5, takeProfitRatio = 1.5 } = input; if (decision.action === "hold") return { allowed: true as const }; if (decision.confidence < confidenceThreshold) return { allowed: false as const, reason: `Fast Momentum requires at least ${confidenceThreshold.toFixed(2)} model confidence` }; if (!enoughBars(context)) return { allowed: false as const, reason: "Fast Momentum requires sufficient provider bars" }; const values = [context!.oneMinute.changePct ?? 0, context!.fiveMinute.changePct ?? 0, context!.fifteenMinute.changePct ?? 0]; if (decision.action === "buy") { if (values.filter(value => value > momentumThreshold).length < 2 || values[0] <= momentumThreshold) return { allowed: false as const, reason: `Fast Momentum requires 1m strength plus one confirmed timeframe outside the neutral zone (±${(momentumThreshold * 100).toFixed(2)}%)` }; const issue = strategyPriceGuards(decision, markPrice, stopLossPct, takeProfitRatio); return issue ? { allowed: false as const, reason: issue } : { allowed: true as const }; } return values.filter(value => value < -momentumThreshold).length < 2 || values[0] >= -momentumThreshold ? { allowed: false as const, reason: `Fast Momentum sell requires 1m weakness plus one confirmed timeframe outside the neutral zone (±${(momentumThreshold * 100).toFixed(2)}%)` } : { allowed: true as const }; }
export function assessRangeReversionDecision(input: { decision: BotDecision; markPrice: number; context: ScalpMarketContext | undefined; confidenceThreshold?: number; rangeUpperBound?: number; rangeLowerBound?: number; stopLossPct?: number; takeProfitRatio?: number }) { const { decision, markPrice, context, confidenceThreshold = 0.6, rangeUpperBound = 0.7, rangeLowerBound = 0.4, stopLossPct = 0.5, takeProfitRatio = 1.5 } = input; if (decision.action === "hold") return { allowed: true as const }; if (decision.confidence < confidenceThreshold) return { allowed: false as const, reason: `Range Reversion requires at least ${confidenceThreshold.toFixed(2)} model confidence` }; if (!enoughBars(context)) return { allowed: false as const, reason: "Range Reversion requires sufficient provider bars" }; const one = context!.oneMinute.changePct ?? 0, five = context!.fiveMinute.changePct ?? 0, fifteen = context!.fifteenMinute.changePct ?? 0; const inRange = Math.abs(five) <= rangeUpperBound && Math.abs(fifteen) <= rangeLowerBound; if (!inRange) return { allowed: false as const, reason: `Range Reversion requires contained 5m/15m movement rather than a directional trend (bounds: ±${(rangeUpperBound * 100).toFixed(1)}% / ±${(rangeLowerBound * 100).toFixed(1)}%)` }; if (decision.action === "buy") { if (one > -.05) return { allowed: false as const, reason: "Range Reversion buy requires a meaningful 1m pullback within the range" }; const issue = strategyPriceGuards(decision, markPrice, stopLossPct, takeProfitRatio); return issue ? { allowed: false as const, reason: issue } : { allowed: true as const }; } return one < .05 ? { allowed: false as const, reason: "Range Reversion sell requires a meaningful 1m bounce within the range" } : { allowed: true as const }; }
export function assessPaperBotDecision(input: { strategy: PaperBotStrategy; decision: BotDecision; markPrice: number; context: ScalpMarketContext | undefined; confidenceThreshold?: number; stopLossPct?: number; takeProfitRatio?: number; momentumThreshold?: number; rangeUpperBound?: number; rangeLowerBound?: number }) { if (input.strategy === "fast_momentum") return assessFastMomentumDecision({ ...input, confidenceThreshold: input.confidenceThreshold, momentumThreshold: input.momentumThreshold, stopLossPct: input.stopLossPct, takeProfitRatio: input.takeProfitRatio }); if (input.strategy === "range_reversion") return assessRangeReversionDecision({ ...input, confidenceThreshold: input.confidenceThreshold, rangeUpperBound: input.rangeUpperBound, rangeLowerBound: input.rangeLowerBound, stopLossPct: input.stopLossPct, takeProfitRatio: input.takeProfitRatio }); return assessScalpingDecision({ ...input, confidenceThreshold: input.confidenceThreshold, stopLossPct: input.stopLossPct, takeProfitRatio: input.takeProfitRatio }); }

const strategyPrompt = (strategy: PaperBotStrategy) => strategy === "learning_mode" ? "Learning Mode is a permissive paper-only training simulation. Return buy for an eligible symbol without a simulated spot position, and sell only to close an existing simulated spot position. Do not return hold solely because momentum, confidence, stops, targets, or a range condition is weak; only hold if the provider mark is unavailable." : strategy === "fast_momentum" ? "Fast Momentum weights 1m movement and accepts one of 5m/15m as confirmation only when two timeframes are materially aligned outside a ±0.04% neutral zone." : strategy === "range_reversion" ? "Range Reversion is allowed only when 5m/15m are contained and the 1m chart makes a meaningful pullback or bounce inside that range." : "Scalp Momentum requires positive or negative 1m execution momentum with both 5m and 15m confirmation.";
export async function requestDeepSeekDecision(input: { marketContext: unknown; configuredSymbols: string[]; strategy?: PaperBotStrategy; fetchImpl?: typeof fetch }): Promise<BotDecision> { const apiKey = process.env.DEEPSEEK_API_KEY; if (!apiKey) throw new Error("DeepSeek analysis is not configured"); const fetchImpl = input.fetchImpl ?? fetch; const configuredSymbols = input.configuredSymbols.filter(symbol => /^[A-Z0-9]{5,24}$/.test(symbol)); const fallbackSymbol = configuredSymbols[0] ?? BOT_DEFAULTS.symbols[0]; const strategy = input.strategy ?? PAPER_SCALPING_STRATEGY; const response = await fetchImpl("https://api.deepseek.com/chat/completions", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ model: "deepseek-v4-flash", stream: false, thinking: { type: "disabled" }, max_tokens: 700, response_format: { type: "json_object" }, messages: [{ role: "system", content: `You analyze provider-returned Binance spot market context for a paper-only ${strategy} simulation. ${strategyPrompt(strategy)} ${strategy === "learning_mode" ? "For a buy, provide a provider-mark-relative stop and target if possible; a training fallback may supply them if omitted." : "For a buy, propose a stop 0.03% to 0.75% below mark and a target with at least 1.2:1 reward-to-risk. For a sell, only propose closing an existing simulated spot position. Use hold whenever confirmation, price availability, or setup quality is insufficient."} Also include an experimental nextCandle estimate for the next one-minute candle using only direction up/down/flat, probability 0 to 1, and a brief reason. Include holdCategory as one of timeframe_conflict, low_volatility, no_qualified_setup, risk_guard, or model_unavailable when action is hold. Both are uncertain context only and MUST NOT imply a real order, account action, leverage, transfer, or financial certainty. Return exactly one non-empty JSON object and no markdown. The symbol field MUST contain exactly one configured symbol from the allowed list, never a comma-separated list or an external pair. Required JSON shape: {"action":"buy","symbol":"BTCUSDT","confidence":0.5,"stopPrice":null,"targetPrice":null,"reason":"brief reason","nextCandle":{"direction":"flat","probability":0.5,"reason":"uncertain momentum"}}. Never return blank.` }, { role: "user", content: `Return JSON for exactly one allowed symbol: ${JSON.stringify(configuredSymbols)}. Market context: ${JSON.stringify(input.marketContext)}` }] }), signal: AbortSignal.timeout(20_000) }); if (!response.ok) throw new Error(`DeepSeek analysis request failed (${response.status})`); const payload = await response.json() as { choices?: Array<{ message?: { content?: string | null } }> }; return constrainDecisionToConfiguredSymbols(parseDeepSeekDecisionContent(payload.choices?.[0]?.message?.content, fallbackSymbol), configuredSymbols); }
