import { useEffect, useMemo, useState } from "react";
import { Bot, BrainCircuit, CircleDollarSign, Clock3, Pause, Play, Radio, RefreshCw, ShieldAlert, ShieldCheck, WifiOff } from "lucide-react";
import { trpc } from "@/lib/trpc";
import PaperBotActivityChart from "@/components/PaperBotActivityChart";

const PAPER_STRATEGIES = ["scalp_momentum", "fast_momentum", "range_reversion", "learning_mode"] as const;
type PaperStrategy = typeof PAPER_STRATEGIES[number];
const money = (value: number | null | undefined) => value === null || value === undefined || !Number.isFinite(value) ? "—" : value.toLocaleString(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 2 });
const percentage = (value: number | null | undefined) => value === null || value === undefined || !Number.isFinite(value) ? "—" : `${value >= 0 ? "+" : ""}${value.toFixed(2)}%`;
const observedTime = (value: number | undefined) => value ? new Date(value).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" }) : "—";
const isPaperStrategy = (value: unknown): value is PaperStrategy => typeof value === "string" && (PAPER_STRATEGIES as readonly string[]).includes(value);
const strategyCopy: Record<PaperStrategy, { title: string; description: string }> = {
  scalp_momentum: { title: "Scalp Momentum", description: "1m trigger · both 5m / 15m confirmations" },
  fast_momentum: { title: "Fast Momentum", description: "1m trigger · one of 5m / 15m confirms" },
  range_reversion: { title: "Range Reversion", description: "1m pullback / bounce inside a contained range" },
  learning_mode: { title: "Learning Mode", description: "Permissive paper entries / exits · valid live marks only" },
};
const holdLabels: Record<string, string> = { timeframe_conflict: "Timeframes conflict", low_volatility: "Low volatility", no_qualified_setup: "No qualified setup", risk_guard: "Paper risk guard", model_unavailable: "Model or provider unavailable" };

export function getPaperBotDisplayState(input: { enabled?: number; lastRunStatus?: string | null; orders?: unknown[] } | undefined) { if (!input) return "loading" as const; if (input.enabled === 1) return "scheduled" as const; if ((input.orders?.length ?? 0) > 0) return "paused" as const; return "ready" as const; }
export function getScalpObservationDisplayState(input: { availability?: string; oneMinute?: { bars?: number }; fiveMinute?: { bars?: number }; fifteenMinute?: { bars?: number } } | undefined) { return input?.availability === "live" && (input.oneMinute?.bars ?? 0) > 0 && (input.fiveMinute?.bars ?? 0) > 0 && (input.fifteenMinute?.bars ?? 0) > 0 ? "live" as const : "unavailable" as const; }
export function getPaperBotRunSummary(run: { status: string; error?: string | null; decision?: string | null }) { try { const decision = run.decision ? JSON.parse(run.decision) as { reason?: unknown; holdCategory?: unknown } : undefined; const reason = typeof decision?.reason === "string" ? decision.reason : undefined; const category = typeof decision?.holdCategory === "string" ? holdLabels[decision.holdCategory] : undefined; return category && reason ? `${category} — ${reason}` : reason ?? run.error ?? "Awaiting completion"; } catch { return run.error ?? "Awaiting completion"; } }
export function getPaperBotQualityStats(runs: Array<{ decision?: string | null }>) { const decisions = runs.flatMap(run => { try { const parsed = run.decision ? JSON.parse(run.decision) as { confidence?: unknown; holdCategory?: unknown } : undefined; return parsed ? [parsed] : []; } catch { return []; } }); const confidence = decisions.flatMap(decision => typeof decision.confidence === "number" && Number.isFinite(decision.confidence) ? [decision.confidence] : []); const band = (predicate: (value: number) => boolean) => confidence.filter(predicate).length; return { decisions: decisions.length, averageConfidence: confidence.length ? confidence.reduce((sum, value) => sum + value, 0) / confidence.length : undefined, under40: band(value => value < .4), mid: band(value => value >= .4 && value < .6), qualified: band(value => value >= .6), modelOrParserHolds: decisions.filter(decision => decision.holdCategory === "model_unavailable").length }; }
export type LearningLedgerFilter = "all" | "open" | "wins" | "losses";
export function matchesLearningLedgerFilter(row: { status: string; realizedPnl: number | null }, filter: LearningLedgerFilter) { if (filter === "all") return true; if (filter === "open") return row.status === "open"; if (filter === "wins") return row.realizedPnl !== null && row.realizedPnl > 0; return row.realizedPnl !== null && row.realizedPnl < 0; }
export const LEARNING_LEDGER_PAGE_SIZE = 10;
export function paginateLearningLedgerRows<T>(rows: T[], page: number, pageSize = LEARNING_LEDGER_PAGE_SIZE) { const total = rows.length; const totalPages = Math.max(1, Math.ceil(total / pageSize)); const currentPage = Math.min(Math.max(1, page), totalPages); const start = (currentPage - 1) * pageSize; return { rows: rows.slice(start, start + pageSize), total, totalPages, currentPage, firstItem: total ? start + 1 : 0, lastItem: Math.min(start + pageSize, total) }; }
const paperQuantity = (value: number | null | undefined) => value === null || value === undefined || !Number.isFinite(value) ? "—" : value.toLocaleString(undefined, { maximumFractionDigits: 6 });

function LiveScalpContext({ symbols }: { symbols: string[] }) {
  const [symbol, setSymbol] = useState(symbols[0] ?? "BTCUSDT");
  useEffect(() => { if (!symbols.includes(symbol)) setSymbol(symbols[0] ?? "BTCUSDT"); }, [symbol, symbols]);
  const observation = trpc.crypto.scalpContext.useQuery({ symbol }, { retry: false, refetchInterval: 5_000, refetchIntervalInBackground: false }); const state = getScalpObservationDisplayState(observation.data);
  const windows = state === "live" ? [{ label: "1m trigger", value: observation.data?.oneMinute }, { label: "5m confirm", value: observation.data?.fiveMinute }, { label: "15m confirm", value: observation.data?.fifteenMinute }] : [];
  return <div className={`bot-live-context ${state}`}><div className="bot-live-context-head"><div><span className="binance-kicker">LIVE STRATEGY CONTEXT</span><b><Radio size={13} /> Public chart observation · 5s refresh</b></div><span className="bot-observation-status">{observation.isFetching ? "REFRESHING" : state === "live" ? "OBSERVING" : "UNAVAILABLE"}</span></div><div className="bot-live-symbols" role="tablist" aria-label="Live paper-bot context pair">{symbols.map(item => <button type="button" key={item} onClick={() => setSymbol(item)} className={symbol === item ? "active" : ""}>{item}</button>)}</div>{state === "live" ? <><div className="bot-live-summary"><span>LAST {money(observation.data?.quote.price)}</span><span className={(observation.data?.quote.changePct ?? 0) >= 0 ? "up" : "down"}>{percentage(observation.data?.quote.changePct)}</span><small>Observed {observedTime(observation.data?.observedAt)}</small></div><div className="bot-live-windows">{windows.map(window => <div key={window.label}><span>{window.label}</span><b className={(window.value?.changePct ?? 0) >= 0 ? "up" : "down"}>{percentage(window.value?.changePct)}</b><small>{window.value?.bars ?? 0} provider bars</small></div>)}</div></> : <div className="bot-live-unavailable"><WifiOff size={14} />{observation.data?.providerError ?? "Public 1m/5m/15m context is currently unavailable. No inferred market state is shown."}</div>}<p><b>Observation only.</b> This view refreshes every five seconds while open. DeepSeek paper decisions still follow the selected managed cadence and never create live orders.</p></div>;
}

export default function BinancePaperBot() {
  const utils = trpc.useUtils(); const tickers = trpc.crypto.tickers.useQuery({ market: "global-spot", limit: 24 }, { retry: false, refetchInterval: 30_000 }); const prices = useMemo(() => Object.fromEntries((tickers.data ?? []).map(item => ({ symbol: item.symbol, price: Number(item.price ?? 0) })).filter(item => item.price > 0).map(item => [item.symbol, item.price] as const)), [tickers.data]);
  const account = trpc.binancePaper.account.useQuery({ prices }, { retry: false, refetchInterval: 15_000 }); const config = trpc.binancePaper.botConfig.useQuery(undefined, { retry: false }); const orders = trpc.binancePaper.orders.useQuery(undefined, { retry: false, refetchInterval: 15_000 }); const ledger = trpc.binancePaper.learningLedger.useQuery(undefined, { retry: false, refetchInterval: 15_000 }); const runs = trpc.binancePaper.botRuns.useQuery(undefined, { retry: false, refetchInterval: 15_000 });
  const [symbols, setSymbols] = useState("BTCUSDT, ETHUSDT, SOLUSDT"); const [interval, setInterval] = useState<1 | 5 | 15>(5); const [strategy, setStrategy] = useState<PaperStrategy>("scalp_momentum"); const [ledgerFilter, setLedgerFilter] = useState<LearningLedgerFilter>("all"); const [ledgerPage, setLedgerPage] = useState(1);
  const [confidenceThreshold, setConfidenceThreshold] = useState(0.60); const [stopLossPct, setStopLossPct] = useState(0.5); const [takeProfitRatio, setTakeProfitRatio] = useState(1.5); const [momentumThreshold, setMomentumThreshold] = useState(0.04); const [rangeUpperBound, setRangeUpperBound] = useState(0.7); const [rangeLowerBound, setRangeLowerBound] = useState(0.4);
  useEffect(() => { if (config.data) { try { const parsed = JSON.parse(config.data.symbols); if (Array.isArray(parsed)) setSymbols(parsed.join(", ")); } catch { /* preserved safely */ } setInterval(config.data.scheduleMinutes as 1 | 5 | 15); if (isPaperStrategy(config.data.strategy)) setStrategy(config.data.strategy); if (typeof config.data.confidenceThreshold === "string") setConfidenceThreshold(parseFloat(config.data.confidenceThreshold)); if (typeof config.data.stopLossPct === "string") setStopLossPct(parseFloat(config.data.stopLossPct)); if (typeof config.data.takeProfitRatio === "string") setTakeProfitRatio(parseFloat(config.data.takeProfitRatio)); if (typeof config.data.momentumThreshold === "string") setMomentumThreshold(parseFloat(config.data.momentumThreshold)); if (typeof config.data.rangeUpperBound === "string") setRangeUpperBound(parseFloat(config.data.rangeUpperBound)); if (typeof config.data.rangeLowerBound === "string") setRangeLowerBound(parseFloat(config.data.rangeLowerBound)); } }, [config.data]);
  const refresh = () => { void account.refetch(); void config.refetch(); void orders.refetch(); void ledger.refetch(); void runs.refetch(); }; const save = trpc.binancePaper.saveBotConfig.useMutation({ onSuccess: refresh }); const enable = trpc.binancePaper.enableBot.useMutation({ onSuccess: refresh }); const pause = trpc.binancePaper.pauseBot.useMutation({ onSuccess: refresh });
  const parsedSymbols = symbols.split(",").map(value => value.trim().toUpperCase()).filter(Boolean); const status = getPaperBotDisplayState({ enabled: config.data?.enabled, lastRunStatus: config.data?.lastRunStatus, orders: orders.data }); const busy = save.isPending || enable.isPending || pause.isPending; const currentStrategy = strategyCopy[strategy]; const quality = useMemo(() => getPaperBotQualityStats(runs.data ?? []), [runs.data]); const visibleLedgerOrders = useMemo(() => (ledger.data?.orders ?? []).filter(row => matchesLearningLedgerFilter(row, ledgerFilter)).slice().reverse(), [ledger.data?.orders, ledgerFilter]); const ledgerPagination = useMemo(() => paginateLearningLedgerRows(visibleLedgerOrders, ledgerPage), [visibleLedgerOrders, ledgerPage]);
  useEffect(() => { if (ledgerPage !== ledgerPagination.currentPage) setLedgerPage(ledgerPagination.currentPage); }, [ledgerPage, ledgerPagination.currentPage]);
  const saveConfig = () => save.mutate({ symbols: parsedSymbols, strategy, scheduleMinutes: interval, riskPct: 1, dailyLossStopPct: 3, maxOpenPositions: 3, confidenceThreshold, stopLossPct, takeProfitRatio, momentumThreshold, rangeUpperBound, rangeLowerBound });
  return <section className="binance-card paper-bot-card" id="binance-paper-bot">
    <div className="binance-card-head"><div><span className="binance-kicker">DEEPSEEK · PAPER ONLY</span><h2><Bot size={18} /> $10,000 paper account</h2></div><button aria-label="Refresh paper account" onClick={refresh}><RefreshCw size={14} className={account.isFetching ? "spin" : ""} /></button></div>
    <div className="paper-bot-banner"><ShieldCheck size={15} /><div><b>Simulation service. No Binance account, API key, or live order path.</b><span>{currentStrategy.title} uses provider-returned 1m / 5m / 15m context and DeepSeek JSON only.</span></div></div>
    <div className="paper-account-grid"><div><span>EQUITY</span><b>{money(account.data?.equity)}</b><small>Starting capital {money(account.data?.initialCapital)}</small></div><div><span>BUYING POWER</span><b>{money(account.data?.buyingPower)}</b><small>{account.data?.positions.length ?? 0} simulated open position(s)</small></div><div><span>DAY P&L</span><b className={(account.data?.dailyPnl ?? 0) >= 0 ? "up" : "down"}>{money(account.data?.dailyPnl)}</b><small>{strategy === "learning_mode" ? "Learning mode does not apply the daily paper-loss stop" : `Hard stop at −${money((account.data?.dailyStartEquity ?? 10_000) * .03)}`}</small></div><div><span>TOTAL P&L</span><b className={(account.data?.realizedPnl ?? 0) + (account.data?.unrealizedPnl ?? 0) >= 0 ? "up" : "down"}>{money((account.data?.realizedPnl ?? 0) + (account.data?.unrealizedPnl ?? 0))}</b><small>Realized {money(account.data?.realizedPnl)}</small></div></div>
    <div className="bot-settings"><div className="bot-settings-head"><div><BrainCircuit size={15} /><b>Scheduled simulation settings</b></div><span className={`bot-status ${status}`}>{status === "scheduled" ? "SCHEDULED" : status === "paused" ? "PAUSED" : "READY"}</span></div><label>GLOBAL SPOT PAIRS<input aria-label="Scheduled paper bot pairs" value={symbols} onChange={event => setSymbols(event.target.value)} placeholder="BTCUSDT, ETHUSDT, SOLUSDT" /></label><div className="bot-control-grid"><div><span>RUN CADENCE</span><div className="bot-intervals">{([1, 5, 15] as const).map(value => <button type="button" key={value} className={interval === value ? "active" : ""} onClick={() => setInterval(value)}>{value}m</button>)}</div><small>Each decision sees 1m · 5m · 15m context.</small></div><div><span>SIMULATION STRATEGY</span><div className="bot-strategy-buttons" role="group" aria-label="Paper simulation strategy">{PAPER_STRATEGIES.map(item => <button type="button" key={item} className={strategy === item ? "active" : ""} onClick={() => setStrategy(item)}>{strategyCopy[item].title}</button>)}</div><b>{currentStrategy.description}</b><small>{strategy === "learning_mode" ? "Learning mode bypasses confidence, momentum, range, daily-stop, exposure, and reward/risk filters. Valid live marks and idempotent paper orders remain required." : "Neutral zone and 1% / 3% paper-risk limits remain active in this mode."}</small></div></div><div className="bot-actions"><button className="bot-secondary" disabled={busy || parsedSymbols.length < 1} onClick={saveConfig}><CircleDollarSign size={14} /> Save paper settings</button>{config.data?.enabled === 1 ? <button className="bot-pause" disabled={busy} onClick={() => pause.mutate()}><Pause size={14} /> Pause simulated bot</button> : <button className="bot-enable" disabled={busy || parsedSymbols.length < 1} onClick={() => enable.mutate({ scheduleMinutes: interval })}><Play size={14} /> Start scheduled simulation</button>}</div>{save.error || enable.error || pause.error ? <div className="bot-error"><ShieldAlert size={14} />{save.error?.message ?? enable.error?.message ?? pause.error?.message}</div> : null}</div>
    <LiveScalpContext symbols={parsedSymbols} /><PaperBotActivityChart symbols={parsedSymbols} orders={orders.data ?? []} runs={runs.data ?? []} />
    <div className="paper-bot-history"><div><span className="binance-kicker">SIMULATION AUDIT · LAST {quality.decisions}</span><h3>Decision quality and latest activity</h3></div>{quality.decisions ? <div className="bot-quality-summary"><span>AVG CONFIDENCE <b>{quality.averageConfidence?.toFixed(2) ?? "—"}</b></span><span>&lt;0.40 <b>{quality.under40}</b></span><span>0.40–0.59 <b>{quality.mid}</b></span><span>≥0.60 <b>{quality.qualified}</b></span><span>MODEL / PARSER HOLD <b>{quality.modelOrParserHolds}</b></span></div> : null}{runs.data?.length ? <div className="bot-run-list">{runs.data.slice(0, 5).map(run => <div key={run.id}><span className={`run-dot ${run.status}`} /><b>{run.status.replace("_", " ")}</b><span>{new Date(run.createdAt).toLocaleString()}</span><small>{getPaperBotRunSummary(run)}</small></div>)}</div> : <div className="binance-empty"><Clock3 size={15} />No scheduled simulation has run yet.</div>}</div>
    <div className="learning-ledger" aria-live="polite"><div className="learning-ledger-head"><div><span className="binance-kicker">SIMULATION AUDIT · ALL LEARNING ORDERS</span><h3>DeepSeek Learning Mode trade ledger</h3><p>Every persisted Learning Mode paper fill is shown. Open entries remain <b>OPEN</b>; only matched simulated exits can be a win or loss.</p></div><span className="learning-ledger-count">{ledger.data?.summary.orders ?? 0} ORDER{(ledger.data?.summary.orders ?? 0) === 1 ? "" : "S"}</span></div>
      <div className="learning-ledger-summary"><span>COMPLETED <b>{ledger.data?.summary.closedTrades ?? 0}</b></span><span className="up">WINS <b>{ledger.data?.summary.wins ?? 0}</b></span><span className="down">LOSSES <b>{ledger.data?.summary.losses ?? 0}</b></span><span>OPEN <b>{ledger.data?.openPositions.length ?? 0}</b></span><span className={(ledger.data?.summary.realizedPnl ?? 0) >= 0 ? "up" : "down"}>REALIZED P&amp;L <b>{money(ledger.data?.summary.realizedPnl)}</b></span></div>
      <div className="learning-ledger-filters" role="group" aria-label="Filter Learning Mode paper orders">{(["all", "open", "wins", "losses"] as const).map(filter => <button type="button" key={filter} aria-pressed={ledgerFilter === filter} className={ledgerFilter === filter ? "active" : ""} onClick={() => { setLedgerFilter(filter); setLedgerPage(1); }}>{filter === "all" ? "All orders" : filter === "open" ? "Open" : filter === "wins" ? "Wins" : "Losses"}</button>)}</div>
      {ledger.isLoading ? <div className="binance-empty"><Clock3 size={15} />Loading Learning Mode order history…</div> : visibleLedgerOrders.length ? <><div className="learning-ledger-list">{ledgerPagination.rows.map(order => { const outcome = order.realizedPnl !== null && order.realizedPnl > 0 ? "win" : order.realizedPnl !== null && order.realizedPnl < 0 ? "loss" : order.status === "open" ? "open" : "entry"; const label = outcome === "win" ? "WIN" : outcome === "loss" ? "LOSS" : outcome === "open" ? "OPEN" : order.status === "exit" ? "EXIT" : "ENTRY"; return <article className={`learning-ledger-row ${outcome}`} key={order.id}><div className="learning-ledger-status"><span>{label}</span><b>{order.symbol}</b><small>{new Date(order.createdAt).toLocaleString()}</small></div><div><span>SIDE</span><b>{order.side.toUpperCase()}</b></div><div><span>AMOUNT</span><b>{money(order.amount)}</b><small>{paperQuantity(order.quantity)} @ {money(order.fillPrice)}</small></div><div><span>REALIZED P&amp;L</span><b className={outcome === "win" ? "up" : outcome === "loss" ? "down" : ""}>{order.realizedPnl === null ? "Pending exit" : money(order.realizedPnl)}</b><small>{outcome === "open" ? "Simulated position remains open" : outcome === "entry" ? "Matched by a later simulated exit" : "Matched Learning Mode exit"}</small></div></article>; })}</div>{ledgerPagination.totalPages > 1 ? <nav className="learning-ledger-pagination" aria-label="Learning Mode order history pagination"><span>SHOWING {ledgerPagination.firstItem}–{ledgerPagination.lastItem} OF {ledgerPagination.total}</span><div><button type="button" onClick={() => setLedgerPage(page => Math.max(1, page - 1))} disabled={ledgerPagination.currentPage === 1}>Previous</button><b>PAGE {ledgerPagination.currentPage} OF {ledgerPagination.totalPages}</b><button type="button" onClick={() => setLedgerPage(page => Math.min(ledgerPagination.totalPages, page + 1))} disabled={ledgerPagination.currentPage === ledgerPagination.totalPages}>Next</button></div></nav> : null}</> : <div className="binance-empty"><Clock3 size={15} />{ledgerFilter === "all" ? "No DeepSeek Learning Mode paper orders have been recorded yet." : `No ${ledgerFilter} Learning Mode paper orders match this filter.`}</div>}</div>
    <div className="paper-bot-footnote">{currentStrategy.title} is a simulation-only learning tool. It cannot send any live Binance order, access a Binance account, or move funds.</div>
  </section>;
}
